# Generated by Django 6.0.3 on 2026-03-15 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0002_alter_assetchunk_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFPDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('client_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='rfp_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('extracted', 'Requirements Extracted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('requirement_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfp_documents', to='knowledge.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_reference', models.CharField(blank=True, max_length=50)),
                ('requirement_text', models.TextField()),
                ('requirement_type', models.CharField(choices=[('technical', 'Technical'), ('commercial', 'Commercial'), ('legal', 'Legal'), ('operational', 'Operational'), ('administrative', 'Administrative'), ('other', 'Other')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Draft'), ('draft', 'Draft Generated'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('draft_response', models.TextField(blank=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField(default=0)),
                ('rfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='rfp.rfpdocument')),
            ],
        ),
    ]
