# Generated by Django 6.0.3 on 2026-03-15 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetchunk',
            options={'ordering': ['asset', 'chunk_index']},
        ),
    ]
